name: Deploy
# Controls when the workflow will run "closed" is used for prmoting changes, "opened"/"synchronize" are needed to warn on drift.
on:
  release:
    types:
    - published

jobs:
  telefonistka:
    runs-on: ubuntu-latest
    container:
      image: odedbenozer/telefonistka:alpine-v0.1.11
    steps:
    - uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - name: Telefonistka
      env:
        GITHUB_OAUTH_TOKEN: ${{ steps.generate-token.outputs.token }}
        APPROVER_GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TEMPLATES_PATH: "/telefonistka/templates/"
      run: |
        /telefonistka/bin/telefonistka \ 
          bump-yaml \
          --auto-merge \
          --triggering-actor "$GITHUB_ACTOR" \
          --triggering-repo "$GITHUB_REPOSITORY" \
          --triggering-repo-sha "$GITHUB_REF" \
          --target-repo "ben10k/telefonistka-demo-argo-live" \
          --target-file "_WORKSPACE/telefonistka-demo-application/values.yaml" \
          --address ".telefonistka-demo-argo-live.image.tag" \
          --replacement-string "$(basename $GITHUB_REF)"
